var MigratoryDataClient={};
MigratoryDataClient.a=function(){return navigator.userAgent&&navigator.userAgent.indexOf("ANTGalio")!==-1?"Opera":navigator.userAgent&&navigator.userAgent.indexOf("Chrome")!==-1&&navigator.userAgent.indexOf("WebKit")!==-1?"WebKit Chrome":navigator.userAgent&&navigator.userAgent.indexOf("Android")!==-1?"WebKit Android":navigator.userAgent&&navigator.userAgent.indexOf("iPhone")!==-1?"WebKit iPhone":navigator.userAgent&&navigator.userAgent.indexOf("WebKit")!==-1?"WebKit":navigator.userAgent&&navigator.userAgent.indexOf("MSIE")!==
-1?"IE":navigator.userAgent&&navigator.userAgent.indexOf("Gecko")!==-1?"Gecko":navigator.userAgent&&navigator.userAgent.indexOf("Opera Mobi")!==-1?"Opera Mobile":navigator.userAgent&&navigator.userAgent.indexOf("Opera Mini")!==-1?"unknown":window.opera?"Opera":"unknown"};MigratoryDataClient.b=function(a){if(!document.body)throw"Error: The document doesn't have a body!";var b=true;if(this.c==="unknown"){b=false;if(a)if(this.d===null)throw"Error: Browser not supported!";else this.d(this.NOTIFY_UNSUPPORTED_BROWSER)}return b};
MigratoryDataClient.e=function(){if(document.readyState==="complete"||document.readyState==="interactive")this.f();else if(document.addEventListener){document.addEventListener("DOMContentLoaded",this.f,false);window.addEventListener("load",this.f,false)}else if(document.attachEvent){document.attachEvent("onreadystatechange",this.f);window.attachEvent("onload",this.f);var a=false;try{a=window.frameElement==null}catch(b){}document.documentElement.doScroll&&a&&this.g()}};
MigratoryDataClient.g=function(){if(!MigratoryDataClient.h){try{document.documentElement.doScroll("left")}catch(a){setTimeout(MigratoryDataClient.g,1);return}MigratoryDataClient.f()}};MigratoryDataClient.i=function(a){this.h?a():this.j.push(a)};MigratoryDataClient.f=function(){if(!MigratoryDataClient.h)if(document.body){MigratoryDataClient.h=true;for(var a=0;a<MigratoryDataClient.j.length;a++)MigratoryDataClient.j[a]();MigratoryDataClient.j=null}else setTimeout(MigratoryDataClient.f,13)};
MigratoryDataClient.k=function(a){var b=window.location.protocol,c=window.location.host,d=window.location.port;if(c.indexOf("localhost")===0)return{l:"localhost:80",m:a+"/"};if(d.length>0&&c.lastIndexOf(":")!==-1)c=c.substring(0,c.lastIndexOf(":"));var e=a.indexOf("//");if(e===-1)return null;var f=a.substring(0,e);if(b!==f)return null;a=a.substring(f.length+2);e=a.indexOf("/");if(e!==-1)a=a.substring(0,e);e=a.lastIndexOf(":");b="";if(e!==-1){b=a.substring(e+1);a=a.substring(0,e)}if(navigator.userAgent&&
navigator.userAgent.indexOf("ANTGalio")!==-1){e=80;if(f==="https:")e=443;if(b!==""&&b!==e&&d!==e)if(b!==d)return null}else if(b!==d)return null;if(a.length<4)return null;var g=-1;e=a.length-1;for(var h=c.length-1;e>=0&&h>=0;e--,h--)if(a.charAt(e)!==c.charAt(h)){g=e;break}d="";if(g===-1)if(e===-1&&h===-1){e=a.indexOf(".");d=a.substring(e+1)}else if(e===-1)if(c.charAt(h-1)===".")d=a;else{e=a.indexOf(".");if(e===-1)return null;d=a.substring(e+1)}else{if(h===-1)if(a.charAt(e-1)===".")d=c;else{e=c.indexOf(".");
if(e===-1)return null;d=c.substring(e+1)}}else{e=a.indexOf(".",g+1);if(e===-1)return null;d=a.substring(e+1)}if(d.length<4||d.indexOf(".")===-1)return null;d+=b.length>0?":"+b:"";a=f+"//"+a+(b.length>0?":"+b:"")+"/";if(this.n>=2){c=d.split(".");if(c.length>=this.n)d=c.slice(-1*this.n).join(".")}return{l:d,m:a}};MigratoryDataClient.o=function(a){return this.k(a)===null};
MigratoryDataClient.p=function(a,b){if(a.name)a=a.name;else{var c=a.toString();a=c.substring(c.indexOf("function")+8,c.indexOf("("));a=a.replace(/^\s+|\s+$/g,"");if(a.length===0)a="anonymous";if(a==="anonymous"&&typeof b==="object")for(var d=0;d<b.length;d++)for(var e in b[d])if(b[d].hasOwnProperty(e)&&typeof b[d][e]==="function")if(b[d][e].toString()===c)return e}return a};
MigratoryDataClient.q=function(a){if(a===null||a===undefined||typeof a==="number"||typeof a==="boolean")return a;else if(typeof a==="string")return'"'+a+'"';else if(typeof a==="function")return this.p(a,this)+"()";else if(a instanceof Array)return this.r(a);var b="{",c=0;for(var d in a){if(c>0)b+=", ";if(a.hasOwnProperty(d))b+=d+":"+this.q(a[d]);c++}b+="}";return b};
MigratoryDataClient.s=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=Math.random()*16|0;return(a=="x"?b:b&3|8).toString(16)})};
MigratoryDataClient.t=function(a,b){var c=MigratoryDataClient.u;if(a>0){if(a<=this.v)c=a*MigratoryDataClient.w-Math.floor(Math.random()*MigratoryDataClient.w);else if(MigratoryDataClient.x===MigratoryDataClient.TRUNCATED_EXPONENTIAL_BACKOFF){a=a-this.v;c=Math.min(MigratoryDataClient.y*Math.pow(2,a)-Math.floor(Math.random()*MigratoryDataClient.y*a),MigratoryDataClient.z)}else c=MigratoryDataClient.y;if(b!==undefined&&c<MigratoryDataClient.u)c=MigratoryDataClient.u}return c};
MigratoryDataClient.a0=function(a,b){var c={};if(b.length>0)for(var d=0;d<b.length;d++)c[b[d]]=a[b[d]];else for(d in a)c[d]=a[d];return c};MigratoryDataClient.a1=function(a){for(var b=a.length,c=a.length-1;c>=0;c--){var d=a.charCodeAt(c);if(d>127&&d<=2047)b++;else if(d>2047&&d<=65535)b+=2}return b};
MigratoryDataClient.a2=function(a){a=String(a);for(var b,c,d,e="",f=0,g=a.length%3;f<a.length;){if((b=a.charCodeAt(f++))>255||(c=a.charCodeAt(f++))>255||(d=a.charCodeAt(f++))>255)throw new TypeError("Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.");b=b<<16|c<<8|d;e+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(b>>18&63)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(b>>12&63)+
"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(b>>6&63)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(b&63)}return g?e.slice(0,g-3)+"===".substring(g):e};
MigratoryDataClient.a3=function(a){a=String(a).replace(/[\t\n\f\r ]+/g,"");if(!/^(?:[A-Za-z\d+\/]{4})*?(?:[A-Za-z\d+\/]{2}(?:==)?|[A-Za-z\d+\/]{3}=?)?$/.test(a))throw new TypeError("Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.");a+="==".slice(2-(a.length&3));for(var b,c="",d,e,f=0;f<a.length;){b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(f++))<<18|"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(f++))<<
12|(d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(f++)))<<6|(e="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(f++)));c+=d===64?String.fromCharCode(b>>16&255):e===64?String.fromCharCode(b>>16&255,b>>8&255):String.fromCharCode(b>>16&255,b>>8&255,b&255)}return c};MigratoryDataClient.a4=function(a){a=MigratoryDataClient.a3(a);return pako.inflateRaw(a,{to:"string"})};
MigratoryDataClient.a5=function(a){a=pako.deflateRaw(a,{to:"string"});return MigratoryDataClient.a2(a)};MigratoryDataClient.a6=function(a,b){for(var c=0;c<a.length;c++)if(a[c]===b)return c;return-1};MigratoryDataClient.a7=function(a){for(var b=[],c=0;c<a.length;c++)b.push(a[c]);return b};MigratoryDataClient.a8=function(a,b){for(var c=[],d=0;d<a.length;d++)this.a6(b,a[d])===-1&&c.push(a[d]);return c};
MigratoryDataClient.a9=function(a,b){for(var c=[],d=0;d<a.length;d++)this.a6(b,a[d])!==-1&&c.push(a[d]);return c};MigratoryDataClient.aa=function(a,b){for(var c=this.a7(a),d=0;d<b.length;d++)this.a6(a,b[d])===-1&&c.push(b[d]);return c};
MigratoryDataClient.ab=function(a,b,c,d,e,f){if(typeof b!=="object"||typeof b.length!=="number")throw"Error: "+a+" - invalid argument; expected a list";if(d!==null&&b.length<d)throw"Error: "+a+" - invalid argument; expected a list with a least "+d+" elements";if(c!==null)for(d=0;d<b.length;d++)if(typeof b[d]!==c)throw"Error: "+a+" - invalid argument; the element on the position '"+d+"' is not of type '"+c+"'";if(typeof e==="object"&&typeof e.test==="function")for(d=0;d<b.length;d++)if(!e.test(b[d]))throw"Error: "+
a+". "+f+"; the element on the position '"+d+"' is the cause of the error";};MigratoryDataClient.r=function(a){for(var b="[",c=0;c<a.length;c++){if(c>0)b+=", ";b+=this.q(a[c])}b+="]";return b};MigratoryDataClient.ac=function(a,b,c,d,e){this.ab(a,b,c,d,/^\/([^\/*]+\/)*([^\/*]+|\*)$/,e)};
MigratoryDataClient.ad=function(a,b){if(a===this.ae.af)this.ag(b);else if(a===this.ae.ah)this.ai(b);else if(a===this.ae.aj)this.ak(b);else if(a===this.ae.al)this.am(b);else if(a!==this.ae.an)if(this.ao!==null)if(this.ao.ap===this.aq&&a===this.ae.aq)this.ar(b);else if(this.ao.ap===this.as&&a===this.ae.as)this.at(b);else this.ao.ap===this.au&&a===this.ae.au&&this.av(b)};
MigratoryDataClient.ar=function(a){var b=a[this.ae.ax];if(b!==undefined)this.ay(this.az,this.b0.b1[b]);else{if(this.b2!==this.b3){b=a[this.ae.b4];if(b===undefined){MigratoryDataClient.ay(this.az,"server subscribe response is missing the session id");return}this.b5=b;b=a[this.ae.b6];if(b!==undefined&&b!==null)if(b==1)MigratoryDataClient.b7=MigratoryDataClient.b8;else if(b==2)MigratoryDataClient.b7=MigratoryDataClient.b9;b=a[this.ae.ba];if(b!==undefined&&b!==null)MigratoryDataClient.bb=b;b=a[this.ae.bc];
if(b!==undefined&&b!==null)MigratoryDataClient.bd=b*1E3*1.4;this.be=a[this.ae.bf];b=this.b2;this.b2=this.b3;this.bh=this.bg=0;this.bi();this.bk(a[this.ae.bj]);var c=this.bl[this.bm].m;a=a[this.ae.bn];if(a!==undefined)c=a;if(b!==this.bo){this.bp.bq[this.bm]!==undefined&&this.bp.bq[this.bm].br++;if(b===null||this.bs)this.bt({type:this.NOTIFY_SERVER_UP,info:c})}else this.bp.bq[this.bm]!==undefined&&this.bp.bq[this.bm].bu++;this.bs=false}this.bv()}};
MigratoryDataClient.at=function(a){a=a[this.ae.ax];a!==undefined?this.ay(this.az,this.b0.b1[a]):this.bv()};MigratoryDataClient.av=function(a){a=a[this.ae.ax];a!==undefined?this.ay(this.az,this.b0.b1[a]):this.bv()};
MigratoryDataClient.ag=function(a){var b=this.ae.bw,c=this.ae.bx,d=this.ae.by,e=this.ae.bz,f=this.ae.c0,g=this.ae.c1,h=this.ae.c2;if(!(a[b]===undefined||a[c]===undefined))if(this.c3[a[b]]!==undefined){this.bk(a[this.ae.bj]);var j=false;if(a[g]!==undefined&&parseInt(a[g])===1)j=true;g=false;if(a[h]!==undefined&&parseInt(a[h])===1)g=true;h=this.MESSAGE_TYPE_UPDATE;if(a[e]!==undefined)h=a[e]==this.c4?this.MESSAGE_TYPE_SNAPSHOT:a[e]==this.c5?this.MESSAGE_TYPE_RECOVERED:a[e]==this.c6?this.MESSAGE_TYPE_HISTORICAL:
this.MESSAGE_TYPE_UPDATE;e="";if(a[d]!==undefined)e=a[d];c=a[c];if(g)if(window.pako)c=this.a4(c);else this.c7("Please include `pako.min.js` package to decompress compressed messages.");b={subject:a[b],content:c,closure:e,replySubject:a[f],retained:j,type:h,qos:MigratoryDataClient.QOS_STANDARD,seq:0,epoch:0,compressed:g};f=this.ae.c8;if(a[f]!==undefined){f=((new Date).getTime()&16777215)-a[f];if(f>-14400000)b.latency=f}if(MigratoryDataClient.b7==MigratoryDataClient.b8&&this.c9(a)==true){f=parseInt(a[this.ae.ca]);
a=parseInt(a[this.ae.cb]);b.qos=MigratoryDataClient.QOS_GUARANTEED;b.seq=a;b.epoch=f;a=this.cc(b.subject,this.c3[b.subject],a,f);if(a=="lower")return;else if(a=="higher"){MigratoryDataClient.cd();return}}else if(MigratoryDataClient.b7==MigratoryDataClient.b9&&this.c9(a)==true){f=parseInt(a[this.ae.ca]);a=parseInt(a[this.ae.cb]);b.qos=MigratoryDataClient.QOS_GUARANTEED;b.seq=a;b.epoch=f;a=this.ce(b.subject,this.c3[b.subject],a,f);if(a=="lower")return}this.bp.bq[this.bm]!==undefined&&this.bp.bq[this.bm].cf++;
this.bt({message:b})}};MigratoryDataClient.c9=function(a){var b=this.ae.cg,c=true;if(a[b]!==undefined&&parseInt(a[b])==MigratoryDataClient.ch)c=false;return c};
MigratoryDataClient.cc=function(a,b,c,d){if(b.seqid!=d){b.seq=c;b.messagesReceivedUntilRecovery++;b.seqid=d;return"in_order"}if(c<=b.seq)return"lower";if(c==b.seq+1){if(b.currentSubscribeType==MigratoryDataClient.ci){b.currentSubscribeType=MigratoryDataClient.cj;a={type:this.NOTIFY_DATA_SYNC,info:a};this.bt(a)}b.seq+=1;b.messagesReceivedUntilRecovery++;return"in_order"}if(b.messagesReceivedUntilRecovery>0)return"higher";b.seq=c;b.messagesReceivedUntilRecovery++;a={type:this.NOTIFY_DATA_RESYNC,info:a};
this.bt(a);return"in_order"};MigratoryDataClient.ce=function(a,b,c,d){if(b.seqid!=d){b.seq=c;b.messagesReceivedUntilRecovery++;b.seqid=d;return"in_order"}if(c<=b.seq)return"lower";if(b.currentSubscribeType==MigratoryDataClient.ci)b.currentSubscribeType=MigratoryDataClient.cj;b.seq=c;b.messagesReceivedUntilRecovery++;return"in_order"};MigratoryDataClient.ay=function(a,b){a=a+", "+b;b=this.bp.bq[this.bm].b1;if(b[a]===undefined)b[a]=1;else b[a]++;this.bh++;this.cd()};
MigratoryDataClient.ai=function(a){var b=this.ae.ck,c=this.ae.bw;if(!(a[b]===undefined||a[c]===undefined)){var d=true,e=this.NOTIFY_SUBSCRIBE_DENY;switch(a[b]){case "a":e=this.NOTIFY_SUBSCRIBE_ALLOW;d=false;break;case "d":b=a[this.ae.ax];if(b!==undefined){if(b==MigratoryDataClient.cl)e=this.NOTIFY_SUBSCRIBE_TIMEOUT}else e=this.NOTIFY_SUBSCRIBE_DENY;break}if(d===true){this.cm=this.a8(this.cm,[a[c]]);delete this.c3[a[c]]}this.bt({type:e,info:a[c]})}};
MigratoryDataClient.bt=function(a){this.cn.push(a);setTimeout(function(){var b=MigratoryDataClient.cn.shift();if("message"in b)MigratoryDataClient.co.call(window,b.message);else MigratoryDataClient.d!==null&&MigratoryDataClient.d.call(window,b)},0)};MigratoryDataClient.ak=function(a){a!==undefined&&a!==null&&Object.keys(a).length>0&&this.cp(a)};MigratoryDataClient.cp=function(a){var b=a[this.ae.by];a=a[this.ae.ck];b!==undefined&&b!==null&&this.bt({type:MigratoryDataClient.cq(a),info:b})};
MigratoryDataClient.am=function(a){var b=a[this.ae.bw];a=a[this.ae.bz];if(MigratoryDataClient.cr==a)for(a=0;a<this.cm.length;a++){b=this.c3[this.cm[a]];var c=b.cacheRecoveryStatus;if(MigratoryDataClient.cs==c||MigratoryDataClient.ct==c||MigratoryDataClient.cu==c)b.nrOfConsecutiveRecovery=0;else{b.messagesReceivedUntilRecovery=0;b.seqid!=Number.MAX_SAFE_INTEGER&&b.nrOfConsecutiveRecovery++}}else{b=this.c3[b];if(b!==null)b.cacheRecoveryStatus=a}};
MigratoryDataClient.cq=function(a){if(a===undefined||a===null)return MigratoryDataClient.NOTIFY_PUBLISH_FAILED;switch(a){case "OK":return MigratoryDataClient.NOTIFY_PUBLISH_OK;case "DENY":return MigratoryDataClient.NOTIFY_PUBLISH_DENIED;default:return MigratoryDataClient.NOTIFY_PUBLISH_FAILED}};
MigratoryDataClient.bk=function(a){if(a!==undefined)if(this.cv==null)this.cv=a;else if(a!==this.cv){this.cv=a;for(a=0;a<this.cm.length;a++)this.c3[this.cm[a]]={seqid:Number.MAX_SAFE_INTEGER,seq:0,history:this.c3[this.cm[a]].history,nrOfConsecutiveRecovery:0,messagesReceivedUntilRecovery:0,cacheRecoveryStatus:MigratoryDataClient.cs,currentSubscribeType:MigratoryDataClient.cj}}};
MigratoryDataClient.cw=function(){this.bp.cx=(new Date).getTime();this.bp.bq[this.bm]!==undefined&&this.bp.bq[this.bm].cy++;this.cz!==null&&this.bi();this.ao!==null&&this.ao.ap===this.an&&this.bv();var a=(new Date).getTime();if(a-this.d0>=this.d1){this.d0=a;a={};a.ap=this.an;this.d2(a)}};MigratoryDataClient.bi=function(){this.cz!==null&&clearTimeout(this.cz);if(this.bd>0)this.cz=setTimeout(function(){MigratoryDataClient.bh++;MigratoryDataClient.cd()},this.bd)};
MigratoryDataClient.cd=function(){this.bp.bq[this.bm]!==undefined&&this.bp.bq[this.bm].d3++;if(this.d4!==null){clearTimeout(this.d4);this.d4=null}this.d5();this.d6();this.d7();if(this.b2!==null)this.b2=this.d8;var a=this.bl[this.bm].m;this.d9.push(this.bl[this.bm]);this.be=this.b5=this.bm=null;this.bg++;if(this.cz!==null){clearTimeout(this.cz);this.cz=null}if(!this.bs&&(this.bg===this.da||this.bg===this.bl.length)){this.bs=true;a={type:this.NOTIFY_SERVER_DOWN,info:a};MigratoryDataClient.d!==null&&
MigratoryDataClient.d.call(window,a)}if(this.bl.length>0){a={};a.ap=this.aq;this.d2(a)}if(this.cm.length>0){a={};a.ap=this.as;a.cm=this.cm;this.d2(a)}};
MigratoryDataClient.db=function(){this.bp.bq[this.bm]!==undefined&&this.bp.bq[this.bm].d3++;if(this.d4!==null){clearTimeout(this.d4);this.d4=null}MigratoryDataClient.dc=null;this.d5();this.d6();this.d7();if(this.b2!==null)this.b2=this.d8;var a=this.bl[this.bm].m;this.d9.push(this.bl[this.bm]);this.be=this.b5=this.bm=null;this.bg++;if(this.cz!==null){clearTimeout(this.cz);this.cz=null}if(!this.bs&&(this.bg===this.da||this.bg===this.bl.length)){this.bs=true;a={type:this.NOTIFY_SERVER_DOWN,info:a};MigratoryDataClient.d!==
null&&MigratoryDataClient.d.call(window,a)}};MigratoryDataClient.dd=function(){this.bv();if(this.bl.length>0){var a={};a.ap=this.aq;this.d2(a)}if(this.cm.length>0){a={};a.ap=this.as;a.cm=this.cm;this.d2(a)}};
MigratoryDataClient.de=function(){this.df();var a=false,b=this.bl[this.bm].m,c=this.o(b);if(!MigratoryDataClient.dg){if(!this.dh||!c)b=this.di(b);if(!c&&!this.dj(b,this.bm))return}var d=c&&!this.dk?this.dl:null,e=null,f=null,g=this.dm,h=this.ae,j=null,i=null;if(MigratoryDataClient.dg){g=this.dn;d=this.dp}else if(this.c==="IE"&&c&&MigratoryDataClient.dq){g=this.dr;h=this.ds;d=this.dt}if(this.b2!==this.b3){if(!MigratoryDataClient.dg)if(this.c==="IE"&&!c)if(this.du){d=this.dv;g=this.dw}else{d=this.dx;
e="MigratoryDataClient0.dy";f=this.dz;g=this.e0;h=this.ds}else if(this.c==="IE"&&MigratoryDataClient.dq&&this.du){a=true;d=this.dv;g=this.e1;h=this.ds}else{g=this.e2;if(this.c==="WebKit Android")g=this.e3;d=c&&!this.dk?this.dl:g;g=this.e4}j=navigator.userAgent;i=this.e5}c="";c+=this.e6(d,e,f,h,this.e7,a,j,i,this.e8);if("/"!==b.substring(b.length-1,b.length))b+="/";a=MigratoryDataClient.t(this.bh,this.aq);this.e9=setTimeout(function(){MigratoryDataClient.e9=null;MigratoryDataClient.ay(MigratoryDataClient.ea,
MigratoryDataClient.ao.ap)},a);g.call(this,b,this.bm,c)};
MigratoryDataClient.eb=function(){this.df();var a=this.bl[this.bm].m,b=this.o(a);if(!MigratoryDataClient.dg){if(!this.dh||!b)a=this.di(a);if(!b&&!this.dj(a,this.bm))return}this.cm=this.aa(this.cm,this.ao.cm);var c=b&&!this.dk?this.dl:null,d=this.dm,e=this.ae;if(MigratoryDataClient.dg){d=this.ec;c=this.dp}else if(this.c==="IE"&&b&&MigratoryDataClient.dq){d=this.dr;e=this.ds;c=this.dt}b="";for(var f=0;f<this.ao.cm.length;f++){var g=this.ao.cm[f];if(this.ao.ed!==undefined&&this.ao.ed===true)this.c3[g]=
{seqid:Number.MAX_SAFE_INTEGER,seq:0,history:this.ao.ee[g],nrOfConsecutiveRecovery:0,messagesReceivedUntilRecovery:0,cacheRecoveryStatus:MigratoryDataClient.cs,currentSubscribeType:MigratoryDataClient.cj};b+=this.ef(g,this.c3[g],c,this.b5,e,this.e8)}if("/"!==a.substring(a.length-1,a.length))a+="/";c=MigratoryDataClient.u;if(MigratoryDataClient.dg===false)c=MigratoryDataClient.t(this.bh,this.as);this.e9=setTimeout(function(){MigratoryDataClient.e9=null;MigratoryDataClient.ay(MigratoryDataClient.ea,
MigratoryDataClient.ao.ap)},c);d.call(this,a,this.bm,b)};
MigratoryDataClient.eg=function(){this.df();var a=this.bl[this.bm].m,b=this.o(a);if(!MigratoryDataClient.dg){if(!this.dh||!b)a=this.di(a);if(!b&&!this.dj(a,this.bm))return}this.cm=this.a8(this.cm,this.ao.cm);if(this.b2!==this.b3){this.bv();for(b=0;b<this.ao.cm.length;b++)delete this.c3[this.ao.cm[b]]}else{var c=b&&!this.dk?this.dl:null,d=this.dm,e=this.ae;if(MigratoryDataClient.dg){c=this.dp;d=this.ec}else if(this.c==="IE"&&b&&MigratoryDataClient.dq&&this.du){d=this.dr;e=this.ds;c=this.dt;if("/"!==
a.substring(a.length-1,a.length))a+="/"}var f="";for(b=0;b<this.ao.cm.length;b++){var g=this.ao.cm[b];f+=this.eh(g,this.c3[g],c,this.b5,e,this.e8);delete this.c3[g]}this.e9=setTimeout(function(){MigratoryDataClient.e9=null;MigratoryDataClient.ay(MigratoryDataClient.ea,MigratoryDataClient.ao.ap)},this.u);d.call(this,a,this.bm,f)}};
MigratoryDataClient.ei=function(){this.df();var a=this.bl[this.bm].m,b=this.o(a);if(!MigratoryDataClient.dg){if(!this.dh||!b)a=this.di(a);if(!b&&!this.dj(a,this.bm))return}if(this.b2!==this.b3)this.bv();else{var c=b&&!this.dk?this.dl:null,d=this.dm,e=this.ae,f=this.be;if(MigratoryDataClient.dg){c=this.dp;d=this.ec;f=null}else if(this.c==="IE"&&b&&MigratoryDataClient.dq&&this.du){d=this.dr;e=this.ds;c=this.dt;if("/"!==a.substring(a.length-1,a.length))a+="/"}b=MigratoryDataClient.ej(this.b5,e,c,f,this.e8);
this.e9=setTimeout(function(){MigratoryDataClient.e9=null;MigratoryDataClient.ay(MigratoryDataClient.ea,MigratoryDataClient.ao.ap)},this.u);d.call(this,a,this.bm,b)}};
MigratoryDataClient.ek=function(){this.df();var a=this.bl[this.bm].m;if(MigratoryDataClient.dg)if(this.b2!==this.b3){a=this.ao.el.closure;if(a!==undefined&&a!==null){a={type:MigratoryDataClient.NOTIFY_PUBLISH_FAILED,info:a};this.bt(a)}}else{var b=this.ec,c=this.em(this.ao.el,this.dp,this.b5,this.ae);if("/"!==a.substring(a.length-1,a.length))a+="/";if(this.a1(c)+12>this.bb){a=this.ao.el.closure;if(a!==undefined&&a!==null){a={type:MigratoryDataClient.NOTIFY_MESSAGE_SIZE_LIMIT_EXCEEDED,info:a};this.bt(a)}}else b.call(this,
a,this.bm,c)}else{a=this.ao.el.closure;if(a!==undefined&&a!==null){a={type:MigratoryDataClient.NOTIFY_PUBLISH_FAILED,info:a};this.bt(a)}}};MigratoryDataClient.bv=function(a){if(this.en.length!==0)if(a!==undefined&&a!==null){if(this.en[0].ap===a){this.en.shift();this.d6();this.eo(false)}}else{this.en.shift();this.d6();this.eo(false)}};MigratoryDataClient.d2=function(a){this.en.push(a);this.ep(false)};
MigratoryDataClient.eo=function(a){this.en.length!==0&&setTimeout(function(){MigratoryDataClient.ep(a)},0)};MigratoryDataClient.ep=function(a){if(this.eq)if(this.b(true))if(!(!a&&(this.ao!==null||this.en.length===0))){this.ao=this.en[0];switch(this.ao.ap){case this.as:this.eb();break;case this.au:this.eg();break;case this.an:this.ei();break;case this.aq:this.de();break;case this.aw:this.ek();this.bv();break;case this.er:this.db();break;case this.es:this.dd();break}}};
MigratoryDataClient.et=function(){this.eq=true;this.eo(false)};
MigratoryDataClient.d5=function(){for(;this.en.length>0;){var a=this.en[0];switch(a.ap){case this.as:var b=this.a8(a.cm,this.cm);if(b.length>0){this.cm=this.aa(this.cm,b);if(a.ed!==undefined&&a.ed===true)for(var c=0;c<b.length;c++)this.c3[b[c]]={seqid:Number.MAX_SAFE_INTEGER,seq:0,history:a.ee[b[c]],nrOfConsecutiveRecovery:0,messagesReceivedUntilRecovery:0,cacheRecoveryStatus:MigratoryDataClient.cs,currentSubscribeType:MigratoryDataClient.cj}}break;case this.au:b=this.a9(a.cm,this.cm);if(b.length>
0){this.cm=this.a8(this.cm,b);for(c=0;c<b.length;c++)delete this.c3[b[c]]}break;case this.aw:if(a.el.closure!==undefined&&a.el.closure!==null){a={type:this.NOTIFY_PUBLISH_FAILED,info:a.el.closure};MigratoryDataClient.d!==null&&MigratoryDataClient.d.call(window,a)}break}this.en.shift()}};
MigratoryDataClient.d6=function(){this.ao=null;if(this.e9!==null){clearTimeout(this.e9);this.e9=null}if(this.eu!==null&&this.eu.readyState&&this.eu.readyState!==4){if(typeof XMLHttpRequest!=="undefined")this.eu.aborted=true;this.eu.abort()}this.eu!==null&&delete this.eu;this.eu=null};
MigratoryDataClient.d7=function(){if(this.ev!==null){var a="";if(this.ev.ew!==undefined)a=this.ev.ew;if(a!=="HTML5")if(a==="XDR_HTML5"){a=document.getElementById("MigratoryDataClient1");a!==null&&a.contentWindow.postMessage("disconnect","*")}else if(this.ev.getElementById){a=this.ev.getElementById("ex");if(a!==null){a.src="";this.ev.body.removeChild(a);delete a;a=null}delete this.ev;this.ev=null;CollectGarbage()}else{if(MigratoryDataClient.dg){this.ev.onmessage=function(){};this.ev.onopen=function(){};
this.ev.onclose=function(){};this.ev.close()}else{if(this.ev.ey!==undefined){clearTimeout(this.ev.ey);this.ev.ey=undefined}this.ev.readyState&&this.ev.readyState!==4&&this.ev.abort();a==="XDR_STREAM"&&this.ev.abort()}delete this.ev;this.ev=null}}};
MigratoryDataClient.ez=function(){this.d6();this.d7();this.b2=this.bm=null;this.cm=[];this.be=this.b5=null;this.d9=[];this.bh=this.bg=0;this.bs=false;this.en=[];this.c3={};this.b7=MigratoryDataClient.f0;if(this.cz!==null){clearTimeout(this.cz);this.cz=null}if(this.d4!==null){clearTimeout(this.d4);this.d4=null}};
MigratoryDataClient.f1=function(){if(this.o(this.bl[this.bm].m)&&!this.dk){if(this.ev!==null){this.ev.responseText="";this.ev.f2=0}}else{this.b2=this.bo;this.d7();this.be=this.b5=null;if(this.bl.length>0){var a={};a.ap=this.aq;this.d2(a)}if(this.cm.length>0){a={};a.ap=this.as;a.cm=this.cm;this.d2(a)}}};MigratoryDataClient.df=function(){if(this.bm===null)this.bm=this.f3()};
MigratoryDataClient.f3=function(){var a=this.a8(this.bl,this.d9);if(a.length===0){this.d9=[];a=this.bl}if(a.length===0)throw"Error: f3() No available servers!";for(var b=0,c=0;c<a.length;c++)b+=a[c].f4;var d=-1;if(b===0)d=Math.floor(a.length*Math.random());else{var e=Math.floor(b*Math.random());for(c=b=0;c<a.length;c++){b+=a[c].f4;if(b>e){d=c;break}}}return this.a6(this.bl,a[d])};
MigratoryDataClient.di=function(a){var b=this.k(a);if(b===null||this.dz!==null&&b.l!==this.dz)throw"Error: Invalid common parent domain of the servers! Cause server is '"+a+"'.";if(this.dz===null){this.dz=b.l;if(b.l.indexOf(":")===-1)document.domain=b.l}return b.m};MigratoryDataClient.dj=function(a,b){var c="MigratoryDataClient2"+b;if(window.frames[c]===undefined||window.frames[c].f5===undefined){this.f6(a,b);return false}return true};
MigratoryDataClient.f6=function(a,b){b="MigratoryDataClient2"+b;var c=document.getElementById(b);if(!c){c=document.createElement("iframe");c.name=b;c.id=b;c.style.display="none";document.body.appendChild(c)}b=MigratoryDataClient.t(this.bh,this.as);this.e9=setTimeout(function(){MigratoryDataClient.e9=null;c.src="";c.parentNode.removeChild(c);MigratoryDataClient.ay(MigratoryDataClient.ea,"iframe")},b);if("/"!==a.substring(a.length-1,a.length))a+="/";c.src=a+"_"+this.f7(this.dz,"f5","MigratoryDataClient.f8")};
MigratoryDataClient.f8=function(){clearTimeout(this.e9);this.e9=null;this.eo(true)};MigratoryDataClient.f9=function(a){return this.dk?new XMLHttpRequest:this.fa(a)};
MigratoryDataClient.fa=function(a){if(a){if(this.fb)this.fb.responseText="";else this.fb={open:function(b,c){b=MigratoryDataClient.fc(c);MigratoryDataClient.fd.connect("0",b.host,b.port,"MigratoryDataClient.fe")},setRequestHeader:function(){},send:function(b){MigratoryDataClient.fd.write("0","POST / HTTP/1.1\r\nContent-Length: "+b.length+"\r\n\r\n"+b)},readyState:4,status:200,responseText:"",abort:function(){this.responseText="";MigratoryDataClient.fd.close("0")}};return this.fb}if(this.ff)this.ff.responseText=
"";else this.ff={open:function(b,c){b=MigratoryDataClient.fc(c);MigratoryDataClient.fd.connect("1",b.host,80,"MigratoryDataClient.fg")},setRequestHeader:function(){},send:function(b){MigratoryDataClient.fd.write("1","POST / HTTP/1.1\r\nContent-Length: "+b.length+"\r\n\r\n"+b)},readyState:4,status:200,responseText:"",abort:function(){this.responseText="";MigratoryDataClient.fd.close("1")}};return this.ff};
MigratoryDataClient.fc=function(a){var b,c;b=a.indexOf("https://")==0?"https://":"http://";a=a.substring(b.length);var d=a.indexOf("/");if(d!=-1){c=a.substring(0,d);a.substring(d)}else c=a;d=c.lastIndexOf(":");if(d!=-1){a=c.substring(d+1);c=c.substring(0,d)}else a=b=="https://"?"443":"80";return{host:c,port:a}};MigratoryDataClient.fg=function(a){if(this.eu){this.eu.responseText+=a;this.fh()}};MigratoryDataClient.fe=function(a){if(this.ev){this.ev.responseText+=a;this.fi()}};
MigratoryDataClient.fj=function(){this.b(false);var a=document.createElement("div");document.body.appendChild(a);var b=document.createElement("div");b.id="MigratoryDataClient3";a.appendChild(b);setTimeout(function(){var c="flash-transport.swf";if(typeof MigratoryDataClientFlashTransport==="string")c=MigratoryDataClientFlashTransport;swfobject.embedSWF(c,"MigratoryDataClient3","0","0","9",false,{readyCallback:"MigratoryDataClient.fk"},{allowFullScreen:false,allowScriptAccess:"always"},{id:"MigratoryDataClient4",
name:"MigratoryDataClient4"})},0)};MigratoryDataClient.fk=function(){MigratoryDataClient.fd=document.getElementById("MigratoryDataClient4");if(!MigratoryDataClient.fd)throw"Error: Could not get the reference of the flash-transport.swf!";MigratoryDataClient.et()};
MigratoryDataClient.dr=function(a,b,c){b=document.getElementById("MigratoryDataClient5");if(b===null){b=document.createElement("iframe");b.id="MigratoryDataClient5";b.style.display="none";document.body.appendChild(b)}var d=(new Date).getTime();b.src=a+"_"+c+d};
MigratoryDataClient.e0=function(a,b,c){this.ev=new ActiveXObject("htmlfile");this.ev.open();MigratoryDataClient.dz.indexOf(":")===-1?this.ev.write("<html><head><script>document.domain='"+MigratoryDataClient.dz+"';<\/script></head><body></body></html>"):this.ev.write("<html><head></head><body></body></html>");this.ev.close();this.ev.parentWindow.MigratoryDataClient0=this;b=this.ev.createElement("iframe");b.id="ex";this.ev.body.appendChild(b);this.ev.fl=0;b.src=a+"_"+c};
MigratoryDataClient.dy=function(a){MigratoryDataClient.fm(a);MigratoryDataClient.ev.fl+=a.length;MigratoryDataClient.ev.fl>=MigratoryDataClient.fn&&MigratoryDataClient.ao===null&&MigratoryDataClient.b2!==MigratoryDataClient.bo&&MigratoryDataClient.f1()};
MigratoryDataClient.e1=function(a,b,c){this.ev={};this.ev.ew="XDR_HTML5";MigratoryDataClient.fl=0;b=document.getElementById("MigratoryDataClient1");if(b===null){b=document.createElement("iframe");b.id="MigratoryDataClient1";b.style.display="none";document.body.appendChild(b)}var d=(new Date).getTime();b.src=a+"_"+c+d};
MigratoryDataClient.fo=function(a){if(a.data.indexOf(MigratoryDataClient.ae.fp)!==-1){MigratoryDataClient.fm(a.data);MigratoryDataClient.fl+=a.data.length;MigratoryDataClient.fl>=MigratoryDataClient.fn&&MigratoryDataClient.ao===null&&MigratoryDataClient.b2!==MigratoryDataClient.bo&&MigratoryDataClient.f1()}};
MigratoryDataClient.dw=function(a,b,c){window.frames["MigratoryDataClient2"+b].f5("window.parent.MigratoryDataClient.ev = new XDomainRequest();");this.ev.f2=0;this.ev.ew="XDR_STREAM";this.ev.onload=function(){MigratoryDataClient.fq()};this.ev.onprogress=function(){MigratoryDataClient.fq()};this.ev.onerror=function(){};this.ev.ontimeout=function(){};try{this.ev.open("POST",a);this.ev.send(c)}catch(d){}};
MigratoryDataClient.fq=function(){var a=this.ev;if(a.responseText){for(var b=a.responseText.substring(a.f2),c=b.indexOf(this.ae.fr);c!==-1;){b=b.substring(0,c);this.fm(b);a.f2+=c+1;b=a.responseText.substring(a.f2);c=b.indexOf(this.ae.fr)}a.f2>=this.fn&&this.ao===null&&this.b2!==this.bo&&this.f1()}};
MigratoryDataClient.e4=function(a,b,c){var d=this.o(a);if(d)this.ev=this.f9(true);else window.frames["MigratoryDataClient2"+b].f5("window.parent.MigratoryDataClient.ev = new XMLHttpRequest();");this.ev.f2=0;this.ev.onreadystatechange=function(){MigratoryDataClient.fi()};this.ev.open("POST",a,true);d&&this.c.indexOf("WebKit")===0&&this.ev.setRequestHeader("Content-Type","text/plain");this.ev.send(c)};
MigratoryDataClient.fi=function(){var a=this.ev;if(!(a===null||a.readyState!==3&&a.readyState!==4||a.status!==200)){if(this.c.indexOf("Opera")!==-1){this.ev.ey!==undefined&&clearTimeout(this.ev.ey);this.ev.ey=setTimeout(function(){MigratoryDataClient.ev.ey=undefined;MigratoryDataClient.fi()},this.fs)}if(a.responseText){for(var b=a.responseText.substring(a.f2),c=b.indexOf(this.ae.fr);c!==-1;){b=b.substring(0,c);this.fm(b);a.f2+=c+1;b=a.responseText.substring(a.f2);c=b.indexOf(this.ae.fr)}a.f2>=this.fn&&
this.ao===null&&this.b2!==this.bo&&this.f1()}}};MigratoryDataClient.ft=function(){if(typeof XMLHttpRequest==="undefined"){try{return new ActiveXObject("Msxml2.XMLHTTP.6.0")}catch(a){}try{return new ActiveXObject("Msxml2.XMLHTTP.3.0")}catch(b){}try{return new ActiveXObject("Msxml2.XMLHTTP")}catch(c){}throw"Error: The browser does not support XMLHttpRequest!";}else return new XMLHttpRequest};
MigratoryDataClient.dm=function(a,b,c){var d=this.o(a);if(d)this.eu=this.f9(false);else window.frames["MigratoryDataClient2"+b].f5("window.parent.MigratoryDataClient.eu = ("+this.ft.toString()+")();");this.eu.onreadystatechange=function(){MigratoryDataClient.fh()};this.eu.open("POST",a,true);d&&this.c.indexOf("WebKit")===0&&this.eu.setRequestHeader("Content-Type","text/plain");if(this.c.indexOf("IE")===0){this.eu.setRequestHeader("Content-Type","text/plain");this.eu.setRequestHeader("Connection",
"close")}this.eu.send(c)};MigratoryDataClient.fh=function(){var a=this.eu;a===null||typeof XMLHttpRequest!=="undefined"&&typeof a.aborted!=="undefined"&&a.aborted!==null&&a.aborted==true||a===null||a.readyState!==4||a.status!==200||a.responseText&&this.fm(a.responseText)};
MigratoryDataClient.dn=function(a,b,c){var d;d=a.substring(0,a.indexOf("://"))==="http"?"ws://"+a.substring(a.indexOf("://")+3)+"WebSocketConnection":"wss://"+a.substring(a.indexOf("://")+3)+"WebSocketConnection-Secure";this.ev=MigratoryDataClient.fu(d);this.dc=MigratoryDataClient.s();this.ev.fv=this.dc;this.ev.onmessage=function(e){MigratoryDataClient.fw(e.data)};this.ev.onopen=function(){MigratoryDataClient.ec(a,b,c)};this.ev.onclose=function(){if(MigratoryDataClient.dc===this.fv){MigratoryDataClient.d6();
MigratoryDataClient.bh++;MigratoryDataClient.bv(MigratoryDataClient.aq);var e=MigratoryDataClient.t(MigratoryDataClient.bh);MigratoryDataClient.d4=setTimeout(function(){MigratoryDataClient.cd()},e)}}};MigratoryDataClient.fu=function(a){if(window.WebSocket)return new WebSocket(a);else if(window.MozWebSocket)return new MozWebSocket(a);return null};MigratoryDataClient.ec=function(a,b,c){this.ev!=null&&this.ev.readyState===1&&this.ev.send(c)};
MigratoryDataClient.fw=function(a){var b=MigratoryDataClient.ev;if(!(b===null||b.readyState!==1))if(a){b=a;for(var c=b.indexOf(MigratoryDataClient.ae.fr);c!==-1;){b=b.substring(0,c);MigratoryDataClient.fm(b);b=a.substring(c+1);c=b.indexOf(MigratoryDataClient.ae.fr)}}};MigratoryDataClient.fm=function(a){for(var b=0,c="\u0000",d={};;){var e=a.indexOf(this.ae.fp,b);if(e===-1)break;if(e-b>0){b=a.substring(b,e);c=b.charAt(0);d=this.fx(b);this.ad(c,d)}b=e+1}this.cw()};
MigratoryDataClient.fx=function(a){if(this.ae.fy[a.charAt(0)]!==undefined){for(var b=1,c={};;){if(b>=a.length)break;var d=a.charAt(b),e=a.indexOf(this.ae.fz,b+1);if(e===-1)return c;if(this.ae.g0[d]!==undefined){b++;var f="";switch(this.ae.g1[d]){case this.b0.g2:f=this.g3(this.ae,a.substring(b,e));break;case this.b0.g4:f=MigratoryDataClient.g5(this.ae,a.substring(b,e));break}b=c[d];if(b===undefined)c[d]=f;else if(c[d]instanceof Array)c[d][c[d].length]=f;else{c[d]=[];c[d][0]=b;c[d][1]=f}}b=e+1}return c}};
MigratoryDataClient.f7=function(a,b,c){var d="";d+=this.ds.g6;d+=this.ds.g7;d+=this.g8(this.ds,a);d+=this.ds.fz;d+=this.ds.g9;d+=this.g8(this.ds,b);d+=this.ds.fz;d+=this.ds.ga;d+=this.g8(this.ds,c);d+=this.ds.fz;d+=this.ds.fp;return d};
MigratoryDataClient.e6=function(a,b,c,d,e,f,g,h,j){var i="";i+=f?d.gb:d.aq;if(a!==null){i+=d.gc;i+=this.gd(d,a);i+=d.fz;if(this.c.indexOf("Opera")!==-1){i+=d.ge;i+=this.gd(d,1);i+=d.fz}}if(b!==null){i+=d.ga;i+=this.g8(d,b);i+=d.fz}if(c!==null){i+=d.g7;i+=this.g8(d,c);i+=d.fz}if(e!==null){i+=d.gf;i+=this.g8(d,e);i+=d.fz}if(g!==null){i+=d.bn;i+=this.g8(d,g);i+=d.fz}if(h!==null){i+=d.gg;i+=this.gd(d,h);i+=d.fz}i+=d.gh;i+=this.gd(d,j);i+=d.fz;i+=d.fp;return i};
MigratoryDataClient.ef=function(a,b,c,d,e,f){var g="";g+=e.as;g+=e.bw;g+=this.g8(e,a);g+=e.fz;if(c!==null){g+=e.gc;g+=this.gd(e,c);g+=e.fz;if(this.c.indexOf("Opera")!==-1){g+=e.ge;g+=this.gd(e,1);g+=e.fz}}if(d!==null){g+=e.b4;g+=this.gd(e,d);g+=e.fz}a=this.gi(b);if(a==MigratoryDataClient.gj){g+=e.gk;g+=this.gd(e,b.history);g+=e.fz}else if(a==MigratoryDataClient.ci){g+=e.ca;g+=this.gd(e,b.seqid);g+=e.fz;g+=e.cb;g+=this.gd(e,b.seq+1);g+=e.fz}g+=e.gh;g+=this.gd(e,f);g+=e.fz;g+=e.fp;return g};
MigratoryDataClient.gi=function(a){var b=MigratoryDataClient.cj;if(a.seqid!=Number.MAX_SAFE_INTEGER)if(a.nrOfConsecutiveRecovery>=MigratoryDataClient.gl){if(a.history>0)b=MigratoryDataClient.gj}else b=MigratoryDataClient.ci;else if(a.history>0)b=MigratoryDataClient.gj;if(b==MigratoryDataClient.cj||b==MigratoryDataClient.gj){a.cacheRecoveryStatus=MigratoryDataClient.cs;a.nrOfConsecutiveRecovery=0}return a.currentSubscribeType=b};
MigratoryDataClient.eh=function(a,b,c,d,e,f){b="";b+=e.au;b+=e.bw;b+=this.g8(e,a);b+=e.fz;if(d!==null){b+=e.b4;b+=this.gd(e,d);b+=e.fz}if(c!==null){b+=e.gc;b+=this.gd(e,c);b+=e.fz}b+=e.gh;b+=this.gd(e,f);b+=e.fz;b+=e.fp;return b};MigratoryDataClient.ej=function(a,b,c,d,e){var f="";f+=b.an;f+=b.b4;f+=this.gd(b,a);f+=b.fz;if(c!==null){f+=b.gc;f+=this.gd(b,c);f+=b.fz}if(d!==null){f+=b.bf;f+=this.gd(b,d);f+=b.fz}f+=b.gh;f+=this.gd(b,e);f+=b.fz;f+=b.fp;return f};
MigratoryDataClient.em=function(a,b,c,d){var e="";e+=d.aw;e+=d.bw;e+=this.g8(d,a.subject);e+=d.fz;var f=a.content;if(a.compressed)if(window.pako){var g=this.a5(f);if(g.length<f.length)f=g;else a.compressed=false}else{this.c7("Please include `pako.min.js` package to use compression feature.");a.compressed=false}e+=d.bx;e+=this.g8(d,f);e+=d.fz;if(a.closure!==undefined&&a.closure!==null){e+=d.by;e+=this.g8(d,a.closure);e+=d.fz}if(a.replySubject!==undefined&&a.replySubject!==null){e+=d.c0;e+=this.g8(d,
a.replySubject);e+=d.fz}if(a.qos!==undefined&&a.qos!==null){if(a.qos==MigratoryDataClient.QOS_GUARANTEED){e+=d.cg;e+=this.gd(d,MigratoryDataClient.gm)}else{e+=d.cg;e+=this.gd(d,MigratoryDataClient.ch)}e+=d.fz}if(a.retained!==undefined&&a.retained!==null){if(a.retained===true){e+=d.c1;e+=this.gd(d,1)}else{e+=d.c1;e+=this.gd(d,0)}e+=d.fz}if(a.compressed!==undefined&&a.compressed!==null)if(a.compressed===true){e+=d.c2;e+=this.gd(d,1);e+=d.fz}if(b!==null){e+=d.gc;e+=this.gd(d,b);e+=d.fz;if(this.c.indexOf("Opera")!==
-1){e+=d.ge;e+=this.gd(d,1);e+=d.fz}}if(c!==null){e+=d.b4;e+=this.gd(d,c);e+=d.fz}e+=d.fp;return e};MigratoryDataClient.ds={};MigratoryDataClient.ds.fp="!";MigratoryDataClient.ds.fr="z";MigratoryDataClient.ds.fz="$";MigratoryDataClient.ds.gn="~";MigratoryDataClient.ds.go=" ";MigratoryDataClient.ds.gp='"';MigratoryDataClient.ds.gq="#";MigratoryDataClient.ds.gr="%";MigratoryDataClient.ds.gs="'";MigratoryDataClient.ds.gt="/";MigratoryDataClient.ds.gu="<";MigratoryDataClient.ds.gv=">";
MigratoryDataClient.ds.gw="[";MigratoryDataClient.ds.gx="\\";MigratoryDataClient.ds.gy="]";MigratoryDataClient.ds.gz="^";MigratoryDataClient.ds.h0="`";MigratoryDataClient.ds.h1="{";MigratoryDataClient.ds.h2="|";MigratoryDataClient.ds.h3="}";MigratoryDataClient.ds.h4="";MigratoryDataClient.ds.as="&";MigratoryDataClient.ds.au="(";MigratoryDataClient.ds.af=")";MigratoryDataClient.ds.an="*";MigratoryDataClient.ds.g6="+";MigratoryDataClient.ds.h5=",";MigratoryDataClient.ds.ah="0";
MigratoryDataClient.ds.gb="2";MigratoryDataClient.ds.aw="5";MigratoryDataClient.ds.aj="8";MigratoryDataClient.ds.al=".";MigratoryDataClient.ds.h6="B";MigratoryDataClient.ds.aq="D";MigratoryDataClient.ds.bw="&";MigratoryDataClient.ds.bx="(";MigratoryDataClient.ds.cb=")";MigratoryDataClient.ds.ca="*";MigratoryDataClient.ds.gc="+";MigratoryDataClient.ds.b4=",";MigratoryDataClient.ds.g7="-";MigratoryDataClient.ds.ga=".";MigratoryDataClient.ds.g9="?";MigratoryDataClient.ds.ax="0";
MigratoryDataClient.ds.h7="1";MigratoryDataClient.ds.c8="2";MigratoryDataClient.ds.ge="3";MigratoryDataClient.ds.by="4";MigratoryDataClient.ds.b6="5";MigratoryDataClient.ds.gf="7";MigratoryDataClient.ds.ck="8";MigratoryDataClient.ds.bf="9";MigratoryDataClient.ds.c1="A";MigratoryDataClient.ds.cg="B";MigratoryDataClient.ds.bz="J";MigratoryDataClient.ds.bn="K";MigratoryDataClient.ds.gg="L";MigratoryDataClient.ds.bc="M";MigratoryDataClient.ds.gk="N";MigratoryDataClient.ds.c0="R";
MigratoryDataClient.ds.gh="S";MigratoryDataClient.ds.bj="[";MigratoryDataClient.ds.ba="G";MigratoryDataClient.ds.c2="H";MigratoryDataClient.ds.h8={};
(function(a){var b=a.h8;b["\u0000"]="y";for(var c=1;c<8;c++)b[String.fromCharCode(c)]=String.fromCharCode(c+39);b["\u0008"]="x";for(c=9;c<21;c++)b[String.fromCharCode(c)]=String.fromCharCode(c+39);b["\u0015"]="=";for(c=22;c<32;c++)b[String.fromCharCode(c)]=String.fromCharCode(c+41);b[a.fp]="I";b[a.fr]="w";b[a.fz]="J";b[a.gn]="K";b[a.go]="L";b[a.gp]="M";b[a.gq]="N";b[a.gr]="O";b[a.gs]="P";b[a.gt]="_";b[a.gu]="Q";b[a.gv]="R";b[a.gw]="S";b[a.gx]="T";b[a.gy]="U";b[a.gz]="V";b[a.h0]="W";b[a.h1]="X";b[a.h2]=
"Y";b[a.h3]="Z";b[a.h4]="v"})(MigratoryDataClient.ds);MigratoryDataClient.ds.h9={};(function(a){for(var b in a.h8)if(a.h8.hasOwnProperty(b))a.h9[a.h8[b]]=b})(MigratoryDataClient.ds);MigratoryDataClient.ae={};MigratoryDataClient.ae.fp="";MigratoryDataClient.ae.fr="\u0019";MigratoryDataClient.ae.fz="\u001e";MigratoryDataClient.ae.gn="\u001f";MigratoryDataClient.ae.ha="\u0000";MigratoryDataClient.ae.hb="\n";MigratoryDataClient.ae.hc="\r";MigratoryDataClient.ae.gp='"';MigratoryDataClient.ae.gx="\\";
MigratoryDataClient.ae.as="\u0001";MigratoryDataClient.ae.au="\u0002";MigratoryDataClient.ae.af="\u0003";MigratoryDataClient.ae.an="\u0004";MigratoryDataClient.ae.g6="\u0005";MigratoryDataClient.ae.h5="\u0006";MigratoryDataClient.ae.ah="\t";MigratoryDataClient.ae.gb="\u000c";MigratoryDataClient.ae.aw="\u0010";MigratoryDataClient.ae.aj="\u0013";MigratoryDataClient.ae.al="\u0008";MigratoryDataClient.ae.h6="\u0017";MigratoryDataClient.ae.aq="\u001a";MigratoryDataClient.ae.bw="\u0001";
MigratoryDataClient.ae.bx="\u0002";MigratoryDataClient.ae.cb="\u0003";MigratoryDataClient.ae.ca="\u0004";MigratoryDataClient.ae.gc="\u0005";MigratoryDataClient.ae.b4="\u0006";MigratoryDataClient.ae.g7="\u0007";MigratoryDataClient.ae.ga="\u0008";MigratoryDataClient.ae.g9="\t";MigratoryDataClient.ae.ax="\u000b";MigratoryDataClient.ae.h7="\u000c";MigratoryDataClient.ae.c8="\u000e";MigratoryDataClient.ae.ge="\u000f";MigratoryDataClient.ae.by="\u0010";MigratoryDataClient.ae.b6="\u0011";
MigratoryDataClient.ae.gf="\u0013";MigratoryDataClient.ae.ck="\u0014";MigratoryDataClient.ae.bf="\u0015";MigratoryDataClient.ae.c1="\u0017";MigratoryDataClient.ae.cg="\u0018";MigratoryDataClient.ae.bn="#";MigratoryDataClient.ae.gg="$";MigratoryDataClient.ae.bc="%";MigratoryDataClient.ae.bz="'";MigratoryDataClient.ae.gk="(";MigratoryDataClient.ae.c0=",";MigratoryDataClient.ae.gh="-";MigratoryDataClient.ae.bj="0";MigratoryDataClient.ae.ba="\u001d";MigratoryDataClient.ae.c2="&";
MigratoryDataClient.ae.h8={};(function(a){var b=a.h8;b[a.fp]="\u0001";b[a.fz]="\u0002";b[a.gn]="\u0003";b[a.ha]="\u0004";b[a.hb]="\u0005";b[a.hc]="\u0006";b[a.gp]="\u0007";b[a.gx]="\u0008";b[MigratoryDataClient.ds.fp]="\t";b[a.fr]="\u000b"})(MigratoryDataClient.ae);MigratoryDataClient.ae.h9={};(function(a){for(var b in a.h8)if(a.h8.hasOwnProperty(b))a.h9[a.h8[b]]=b})(MigratoryDataClient.ae);MigratoryDataClient.ae.fy={};
(function(a){a.fy[a.as]=true;a.fy[a.au]=true;a.fy[a.af]=true;a.fy[a.an]=true;a.fy[a.g6]=true;a.fy[a.h5]=true;a.fy[a.ah]=true;a.fy[a.gb]=true;a.fy[a.aw]=true;a.fy[a.aj]=true;a.fy[a.al]=true;a.fy[a.h6]=true;a.fy[a.aq]=true})(MigratoryDataClient.ae);MigratoryDataClient.ae.g0={};
(function(a){a.g0[a.bw]=true;a.g0[a.bx]=true;a.g0[a.cb]=true;a.g0[a.ca]=true;a.g0[a.gc]=true;a.g0[a.b4]=true;a.g0[a.g7]=true;a.g0[a.ga]=true;a.g0[a.g9]=true;a.g0[a.ax]=true;a.g0[a.h7]=true;a.g0[a.c8]=true;a.g0[a.ge]=true;a.g0[a.b6]=true;a.g0[a.gf]=true;a.g0[a.ck]=true;a.g0[a.bf]=true;a.g0[a.bz]=true;a.g0[a.bn]=true;a.g0[a.gg]=true;a.g0[a.by]=true;a.g0[a.gk]=true;a.g0[a.bc]=true;a.g0[a.c0]=true;a.g0[a.gh]=true;a.g0[a.bj]=true;a.g0[a.c1]=true;a.g0[a.cg]=true;a.g0[a.ba]=true;a.g0[a.c2]=true})(MigratoryDataClient.ae);
MigratoryDataClient.b0={};MigratoryDataClient.b0.hd=1;MigratoryDataClient.b0.he=2;MigratoryDataClient.b0.g4=3;MigratoryDataClient.b0.g2=4;MigratoryDataClient.b0.hf={};(function(a){var b=a.hf;b.bw=a.g4;b.bx=a.g4;b.cb=a.g2;b.ca=a.g2;b.gc=a.g2;b.b4=a.g2;b.g7=a.g4;b.ga=a.g4;b.g9=a.g4;b.ax=a.g2;b.h7=a.g4;b.c8=a.g2;b.ge=a.g2;b.gf=a.g4;b.ck=a.g4;b.bf=a.g2;b.bz=a.g4;b.bn=a.g4;b.gg=a.g2;b.by=a.g4;b.b6=a.g2;b.bc=a.g2;b.c0=a.g4;b.gh=a.g2;b.bj=a.g4;b.c1=a.g2;b.cg=a.g2;b.ba=a.g2;b.c2=a.g2})(MigratoryDataClient.b0);
MigratoryDataClient.ae.g1={};MigratoryDataClient.ds.g1={};(function(){for(var a in MigratoryDataClient.b0.hf)if(MigratoryDataClient.b0.hf.hasOwnProperty(a)){MigratoryDataClient.ae.g1[MigratoryDataClient.ae[a]]=MigratoryDataClient.b0.hf[a];MigratoryDataClient.ds.g1[MigratoryDataClient.ds[a]]=MigratoryDataClient.b0.hf[a]}})();MigratoryDataClient.b0.b1={};MigratoryDataClient.b0.b1[0]="UNKNOWN_SESSION_ID";
MigratoryDataClient.g8=function(a,b){for(var c="",d=0;d<b.length;d++){var e=a.h8[b.charAt(d)];if(e!==undefined){c+=a.gn;c+=e}else c+=b.charAt(d)}return c};MigratoryDataClient.g5=function(a,b){for(var c="",d=0;d<b.length;d++){var e=b.charAt(d);if(e===a.gn){if(d+1>=b.length||a.h9[b.charAt(d+1)]===undefined)throw"Error: g5() Illegal argument '"+b+"'!";e=a.h9[b.charAt(d+1)];d++}c+=e}return c};
MigratoryDataClient.gd=function(a,b){if((b&4294967168)===0){var c=String.fromCharCode(b),d=a.h8[c];return d===undefined?c:a.gn+d}var e;e=(b&4278190080)!==0?24:(b&16711680)!==0?16:8;c=[];for(d=0;d<10;d++)c.push(0);for(var f=0,g=0;e>=0;){var h=b>>e&255;g++;c[f]|=h>>g;d=a.h8[String.fromCharCode(c[f])];if(d!==undefined){c[f]=a.gn.charCodeAt(0);c[f+1]=d.charCodeAt(0);f++}f++;c[f]|=h<<7-g&127;e-=8}d=a.h8[String.fromCharCode(c[f])];if(d!==undefined){c[f]=a.gn.charCodeAt(0);c[f+1]=d.charCodeAt(0);f++}f++;
a="";for(d=0;d<f;d++)a+=String.fromCharCode(c[d]);return a};
MigratoryDataClient.g3=function(a,b){var c="Error: g3() Illegal argument '"+b+"'!",d=0,e=-1,f=0,g,h=b.length,j=0;if(h===1)return b.charCodeAt(0);else if(h===2&&b.charAt(0)===a.gn){g=a.h9[b.charAt(1)];if(g!==undefined)return g.charCodeAt(0);else throw c;}for(;h>0;h--){g=b.charAt(j);j++;if(g===a.gn){if(h-1<0)throw c;h--;g=b.charAt(j);j++;g=a.h9[g];if(g===undefined)throw c;}else g=g;if(e>0){f|=g.charCodeAt(0)>>e;d=d<<8|f;f=g.charCodeAt(0)<<8-e}else f=g.charCodeAt(0)<<-e;e=(e+7)%8}return d};
MigratoryDataClient.NOTIFY_UNSUPPORTED_BROWSER="NOTIFY_UNSUPPORTED_BROWSER";MigratoryDataClient.NOTIFY_SERVER_DOWN="NOTIFY_SERVER_DOWN";MigratoryDataClient.NOTIFY_SERVER_UP="NOTIFY_SERVER_UP";MigratoryDataClient.NOTIFY_DATA_RESYNC="NOTIFY_DATA_RESYNC";MigratoryDataClient.NOTIFY_DATA_SYNC="NOTIFY_DATA_SYNC";MigratoryDataClient.NOTIFY_PUBLISH_OK="NOTIFY_PUBLISH_OK";MigratoryDataClient.NOTIFY_PUBLISH_FAILED="NOTIFY_PUBLISH_FAILED";MigratoryDataClient.NOTIFY_PUBLISH_DENIED="NOTIFY_PUBLISH_DENIED";
MigratoryDataClient.NOTIFY_MESSAGE_SIZE_LIMIT_EXCEEDED="NOTIFY_MESSAGE_SIZE_LIMIT_EXCEEDED";MigratoryDataClient.NOTIFY_SUBSCRIBE_ALLOW="NOTIFY_SUBSCRIBE_ALLOW";MigratoryDataClient.NOTIFY_SUBSCRIBE_DENY="NOTIFY_SUBSCRIBE_DENY";MigratoryDataClient.NOTIFY_SUBSCRIBE_TIMEOUT="NOTIFY_SUBSCRIBE_TIMEOUT";MigratoryDataClient.CONSTANT_WINDOW_BACKOFF="CONSTANT_WINDOW_BACKOFF";MigratoryDataClient.TRUNCATED_EXPONENTIAL_BACKOFF="TRUNCATED_EXPONENTIAL_BACKOFF";MigratoryDataClient.QOS_STANDARD="QOS_STANDARD";
MigratoryDataClient.QOS_GUARANTEED="QOS_GUARANTEED";MigratoryDataClient.MESSAGE_TYPE_SNAPSHOT="MESSAGE_TYPE_SNAPSHOT";MigratoryDataClient.MESSAGE_TYPE_UPDATE="MESSAGE_TYPE_UPDATE";MigratoryDataClient.MESSAGE_TYPE_RECOVERED="MESSAGE_TYPE_RECOVERED";MigratoryDataClient.MESSAGE_TYPE_HISTORICAL="MESSAGE_TYPE_HISTORICAL";
MigratoryDataClient.connect=function(){if(this.hg)throw"Error: connect() - already connected";if(this.bl===undefined||this.bl===null||this.bl.length==0)throw"Error: connect() - no server to connect to; use setServers() to specify one or more servers";if(this.co===undefined||this.co===null)throw"Error: connect() - no message handler; use setMessageHandler() to specify a message handler";if(this.d===undefined||this.d===null)throw"Error: connect() - no status handler; use setStatusHandler() to specify a status handler";
this.hg=true;var a={};a.ap=this.aq;this.d2(a);if(this.hh.length>0){a={};a.ap=this.as;a.cm=this.a7(this.hh);a.ee=this.a0(this.hi,[]);a.ed=true;this.d2(a)}};MigratoryDataClient.notifyAfterFailedConnectionAttempts=function(a){if(this.hg)throw"Error: notifyAfterFailedConnectionAttempts() - already connected; use this method before connect()";if(typeof a!=="number"||a<1)throw"Error: notifyAfterFailedConnectionAttempts() - invalid argument; expected a positive integer";this.da=a};
MigratoryDataClient.setServers=function(a){if(this.hg)throw"Error: setServers() - already connected; use this method before connect()";this.ab("setServers",a,"string",1,/^(\d+)?\s*https?:\/\/(\w|-)+(\.(\w|-)+)*(:\d+)?$/i,"Error: setServers() - invalid argument; expected a list of URLs");for(var b=[],c=0;c<a.length;c++){var d=/https?:\/\/(\w|-)+(\.(\w|-)+)*(:\d+)?$/i.exec(a[c])[0],e=/^\d+/.exec(a[c]);if(e===null)e=100;else{e=parseInt(e[0]);if(e>100)throw"Error: setServers() - invalid weight; expected a number between 0 and 100";
}this.dh||this.di(d);b.push({m:d,f4:e})}this.bl=b;this.bp.bq=[];for(c=0;c<a.length;c++){this.bp.bq[c]={};this.bp.bq[c].br=0;this.bp.bq[c].d3=0;this.bp.bq[c].bu=0;this.bp.bq[c].cy=0;this.bp.bq[c].cf=0;this.bp.bq[c].b1={}}};MigratoryDataClient.getSubjects=function(){return this.a7(this.hh)};
MigratoryDataClient.setMessageHandler=function(a){if(this.hg)throw"Error: setMessageHandler() - already connected; use this method before connect()";if(typeof a!=="function")throw"Error: setMessageHandler() - invalid argument; expected a function";this.co=a};
MigratoryDataClient.setStatusHandler=function(a){if(this.hg)throw"Error: setStatusHandler() - already connected; use this method before connect()";if(typeof a!=="function")throw"Error: setStatusHandler() - invalid argument; expected a function";this.d=a};MigratoryDataClient.setLogHandler=function(a){if(typeof a!=="function")throw"Error: setLogHandler() - invalid argument; expected a function";this.c7=a};MigratoryDataClient.subscribe=function(a){MigratoryDataClient.subscribeWithHistory(a,0)};
MigratoryDataClient.subscribeWithHistory=function(a,b){this.ac("subscribeWithHistory",a,"string",1,"Error: subscribe() - invalid first argument; expected a list of valid topics");if(typeof b!=="number"||b<0)throw"Error: subscribeWithHistory() - invalid second argument; expected an integer higher or equal to 0";a=this.a8(a,this.hh);if(a.length!==0){for(var c=0;c<a.length;c++)this.hi[a[c]]=b;this.hh=this.aa(this.hh,a);if(this.hg){b={};b.ap=this.as;b.cm=a;b.ee=this.a0(this.hi,a);b.ed=true;this.d2(b)}}};
MigratoryDataClient.unsubscribe=function(a){this.ac("unsubscribe",a,"string",1,"Error: unsubscribe() - invalid argument; expected a list of valid topics");a=this.a9(a,this.hh);if(a.length!==0){for(var b=0;b<a.length;b++)delete this.hi[a[b]];this.hh=this.a8(this.hh,a);if(this.hg){b={};b.ap=this.au;b.cm=a;this.d2(b)}}};MigratoryDataClient.disconnect=function(){if(this.hg){this.hg=false;this.b(false)&&this.ez()}};
MigratoryDataClient.setEntitlementToken=function(a){if(this.hg)throw"Error: setEntitlementToken() - already connected; use this method before connect()";this.e7=a};
MigratoryDataClient.setNumberOfSubdomainLevels=function(a){if(this.hg)throw"Error: setNumberOfSubdomainLevels() - already connected; use this method before connect()";if(this.bl.length>0)throw"Error: setNumberOfSubdomainLevels() - unable to set the number of subdomain levels when servers are already configured; use this method before setServers()";if(typeof a!=="number"||a<2)throw"Error: setNumberOfSubdomainLevels() - invalid argument; expected an integer higher or equal to 2";this.n=a};
MigratoryDataClient.getInfo=function(){if(!this.hg)throw"Error: getInfo() - not connected; use this method after connect()";s="Date: "+(new Date).toString()+"\n";s+="Uptime: "+((new Date).getTime()-this.bp.hj)+" ms\n";s+="window.location: "+window.location+"\n";s+="document.domain: "+document.domain+"\n";s+="User-agent: "+navigator.userAgent+"\n";s+="Detected browser: "+this.c+"\n";s+="Servers: ";for(var a=0;a<this.bl.length;a++){if(a>0)s+=", ";s+=this.bl[a].f4+" "+this.bl[a].m}s+="\nSubjects: "+
this.cm.toString()+"\n";s+="Connection status ["+(this.bm===null?null:this.bl[this.bm].m)+"]: "+this.b2+"\n";s+="Time from last server activity: "+(this.bp.cx!==null?(new Date).getTime()-this.bp.cx:null)+" ms\n";s+="Servers down before notify: "+this.da+"\n";s+="Consecutive server down count: "+this.bg+" times\n";for(a=0;a<this.bp.bq.length;a++){s+="\nServer up ["+this.bl[a].m+"]: "+this.bp.bq[a].br+" times\n";s+="Server down ["+this.bl[a].m+"]: "+this.bp.bq[a].d3+" times\n";s+="Server connection recycled ["+
this.bl[a].m+"]: "+this.bp.bq[a].bu+" times\n";s+="Received server events ["+this.bl[a].m+"]: "+this.bp.bq[a].cy+"\n";s+="Received messages ["+this.bl[a].m+"]: "+this.bp.bq[a].cf+"\n";for(var b in this.bp.bq[a].b1)if(this.bp.bq[a].b1.hasOwnProperty(b))s+="Error ["+this.bl[a].m+"] x"+this.bp.bq[a].b1[b]+" times : "+b+"\n"}return s};
MigratoryDataClient.publish=function(a){if(!this.hg)throw"Error: publish() - not connected; use this method after connect()";if(a===undefined||a===null)throw"Error: publish() - invalid argument; expected a valid message";if(a.subject===undefined||a.subject===null)throw"Error: publish() - invalid argument; expected a valid message with a non-empty topic";this.ac("publish",[a.subject],"string",1,"Error: publish() - invalid argument; expected a valid subject,  "+a.subject+" is the cause of the error");
if(a.content===undefined||a.content===null)throw"Error: publish() - invalid argument; expected a valid message with a non-empty content";if(a.replySubject!==undefined&&a.replySubject!==null){this.ac("publish",[a.replySubject],"string",1,"Error: publish() - invalid argument; expected a valid replySubject,  "+a.replySubject+" is the cause of the error");MigratoryDataClient.subscribe([a.replySubject])}var b={};b.ap=this.aw;b.el=a;this.d2(b)};
MigratoryDataClient.setQuickReconnectMaxRetries=function(a){if(this.hg)throw"Error: setQuickReconnectMaxRetries() - already connected; use this method before connect()";if(typeof a!=="number"||a<2)throw"Error: setQuickReconnectMaxRetries() - invalid argument; expected an integer higher or equal to 2";this.v=a};
MigratoryDataClient.setQuickReconnectInitialDelay=function(a){if(this.hg)throw"Error: setQuickReconnectInitialDelay() - already connected; use this method before connect()";if(typeof a!=="number"||a<1)throw"Error: setQuickReconnectInitialDelay() - invalid argument; expected an integer higher or equal to 1";this.w=a*1E3};
MigratoryDataClient.setReconnectPolicy=function(a){if(this.hg)throw"Error: setReconnectPolicy()  - already connected; use this method before connect()";if(a===undefined||a!==MigratoryDataClient.CONSTANT_WINDOW_BACKOFF&&a!==MigratoryDataClient.TRUNCATED_EXPONENTIAL_BACKOFF)throw"Error: setReconnectPolicy() - invalid argument; expected CONSTANT_WINDOW_BACKOFF or TRUNCATED_EXPONENTIAL_BACKOFF";this.x=a};
MigratoryDataClient.setReconnectTimeInterval=function(a){if(this.hg)throw"Error: setReconnectTimeInterval() - already connected; use this method before connect()";if(typeof a!=="number"||a<1)throw"Error: setReconnectTimeInterval() - invalid argument; expected an integer higher or equal to 1";this.y=a*1E3};
MigratoryDataClient.setReconnectMaxDelay=function(a){if(this.hg)throw"Error: setReconnectMaxDelay() - already connected; use this method before connect()";if(typeof a!=="number"||a<1)throw"Error: setReconnectMaxDelay() - invalid argument; expected an integer higher or equal to 1";this.z=a*1E3};MigratoryDataClient.pause=function(){if(!this.hg)throw"Error: pause() - not connected; use this method after connect()";if(MigratoryDataClient.hk!=false){MigratoryDataClient.hk=false;var a={};a.ap=this.er;this.d2(a)}};
MigratoryDataClient.resume=function(){if(!this.hg)throw"Error: resume() - not connected; use this method after connect()";if(MigratoryDataClient.hk!=true){MigratoryDataClient.hk=true;var a={};a.ap=this.es;this.d2(a)}};if(!Number.MAX_SAFE_INTEGER)Number.MAX_SAFE_INTEGER=Math.pow(2,53)-1;MigratoryDataClient.e8=601001;MigratoryDataClient.dh=false;MigratoryDataClient.dk=false;MigratoryDataClient.dq=false;MigratoryDataClient.d1=9E5;MigratoryDataClient.hm=3E4+Math.floor(Math.random()*1E4);
MigratoryDataClient.bd=MigratoryDataClient.hm;MigratoryDataClient.u=1E4;MigratoryDataClient.fs=100;MigratoryDataClient.fn=524288;MigratoryDataClient.da=1;MigratoryDataClient.n=0;MigratoryDataClient.b7=MigratoryDataClient.f0;MigratoryDataClient.gl=2;MigratoryDataClient.v=3;MigratoryDataClient.w=5E3;MigratoryDataClient.x=MigratoryDataClient.TRUNCATED_EXPONENTIAL_BACKOFF;MigratoryDataClient.y=2E4;MigratoryDataClient.z=36E4;MigratoryDataClient.e7=null;MigratoryDataClient.cv=null;
MigratoryDataClient.hk=true;MigratoryDataClient.as="SUBSCRIBE";MigratoryDataClient.au="UNSUBSCRIBE";MigratoryDataClient.an="PING";MigratoryDataClient.aq="CONNECT";MigratoryDataClient.aw="PUBLISH";MigratoryDataClient.er="PAUSE";MigratoryDataClient.es="RESUME";MigratoryDataClient.hn=0;MigratoryDataClient.dx=1;MigratoryDataClient.e2=2;MigratoryDataClient.dl=3;MigratoryDataClient.ho=4;MigratoryDataClient.e3=5;MigratoryDataClient.hp=6;MigratoryDataClient.hq=7;MigratoryDataClient.dp=8;
MigratoryDataClient.dv=9;MigratoryDataClient.dt=10;MigratoryDataClient.b3="SERVER_UP";MigratoryDataClient.d8="SERVER_DOWN";MigratoryDataClient.bo="SERVER_RECYCLE";MigratoryDataClient.f0=0;MigratoryDataClient.b8=1;MigratoryDataClient.b9=2;MigratoryDataClient.ch=0;MigratoryDataClient.gm=1;MigratoryDataClient.c4="1";MigratoryDataClient.hr="2";MigratoryDataClient.c5="3";MigratoryDataClient.c6="4";MigratoryDataClient.e5=1;MigratoryDataClient.ea="ERROR_TIMEOUT";MigratoryDataClient.hs="ERROR_HTTP";
MigratoryDataClient.az="ERROR_SERVER";MigratoryDataClient.cj="SUBSCRIBE_TYPE_NORMAL";MigratoryDataClient.gj="SUBSCRIBE_TYPE_HISTORY";MigratoryDataClient.ci="SUBSCRIBE_TYPE_RECOVERY";MigratoryDataClient.cs="cache_ok";MigratoryDataClient.cu="cache_ok_no_new_message";MigratoryDataClient.ct="cache_ok_new_epoch";MigratoryDataClient.ht="no_cache";MigratoryDataClient.hu="no_seq";MigratoryDataClient.cr="end";MigratoryDataClient.hv=0;MigratoryDataClient.hw=1;MigratoryDataClient.cl=2;
MigratoryDataClient.c=MigratoryDataClient.a();MigratoryDataClient.dz=null;MigratoryDataClient.bl=[];MigratoryDataClient.co=null;MigratoryDataClient.d=null;MigratoryDataClient.cn=[];MigratoryDataClient.bb=Number.MAX_SAFE_INTEGER;MigratoryDataClient.eq=false;MigratoryDataClient.j=[];MigratoryDataClient.h=false;MigratoryDataClient.bm=null;MigratoryDataClient.b2=null;MigratoryDataClient.hh=[];MigratoryDataClient.hi={};MigratoryDataClient.cm=[];MigratoryDataClient.c3={};MigratoryDataClient.b5=null;
MigratoryDataClient.be=null;MigratoryDataClient.ev=null;MigratoryDataClient.d0=(new Date).getTime();MigratoryDataClient.cz=null;MigratoryDataClient.d9=[];MigratoryDataClient.bg=0;MigratoryDataClient.bh=0;MigratoryDataClient.bs=false;MigratoryDataClient.dc=null;MigratoryDataClient.en=[];MigratoryDataClient.ao=null;MigratoryDataClient.eu=null;MigratoryDataClient.e9=null;MigratoryDataClient.d4=null;MigratoryDataClient.bp={};MigratoryDataClient.bp.hj=(new Date).getTime();MigratoryDataClient.bp.cx=null;
MigratoryDataClient.bp.bq=[];MigratoryDataClient.dg=false;MigratoryDataClient.du=false;MigratoryDataClient.hg=false;MigratoryDataClient.c7=function(a){window.console&&console.log(a)};if(window.WebSocket)MigratoryDataClient.dg=true;else if(window.MozWebSocket)MigratoryDataClient.dg=true;if(typeof MigratoryDataClient_Disable_WebSocket_Transport!=="undefined"&&MigratoryDataClient_Disable_WebSocket_Transport==true)MigratoryDataClient.dg=false;
if(MigratoryDataClient.dg==false)if(window.XDomainRequest){var xdrTest=new XDomainRequest;try{xdrTest.open("GET",window.location.protocol+"//127.0.0.1");xdrTest.send();MigratoryDataClient.du=true;xdrTest.abort()}catch(e$$7){xdrTest.abort();MigratoryDataClient.du=false}}else MigratoryDataClient.du=false;
if(MigratoryDataClient.c==="IE")try{window.attachEvent("onunload",function(){MigratoryDataClient.ez()})}catch(e$$8){window.addEventListener("unload",function(){MigratoryDataClient.ez()},false)}else window.addEventListener("unload",function(){MigratoryDataClient.ez()},false);MigratoryDataClient.e();if(MigratoryDataClient.c==="WebKit iPhone")MigratoryDataClient.fn=65536;else if(MigratoryDataClient.c==="Opera Mobile"){MigratoryDataClient.fn=32768;MigratoryDataClient.fs=500}
if(MigratoryDataClient.dg==true){MigratoryDataClient.dh=true;MigratoryDataClient.dk=true;MigratoryDataClient.dq=true}else if(MigratoryDataClient.du&&window.postMessage){MigratoryDataClient.dh=true;MigratoryDataClient.dk=true;MigratoryDataClient.dq=true;try{window.attachEvent("onmessage",MigratoryDataClient.fo)}catch(e$$9){window.addEventListener("onmessage",MigratoryDataClient.fo,false)}}else if(XMLHttpRequest&&(new XMLHttpRequest).withCredentials!==undefined){MigratoryDataClient.dh=true;MigratoryDataClient.dk=
true}else if(swfobject&&swfobject.hasFlashPlayerVersion("9")&&(typeof MigratoryDataClient_Allow_Flash_Transport==="undefined"||MigratoryDataClient_Allow_Flash_Transport==true)){MigratoryDataClient.dh=true;MigratoryDataClient.i(function(){MigratoryDataClient.fj()})}if(!MigratoryDataClient.dh||MigratoryDataClient.dk)MigratoryDataClient.i(function(){MigratoryDataClient.et()});
